apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::087780137217:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::087780137217:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UH68NZ1A8MAX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-06T16:03:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-04-06T16:03:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1658"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b8f26953-bb4a-454b-9fdb-328370ba4472
